name: Update Resume Gist

on: push

permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write
  
jobs:
  update-resume-gist:
    
    runs-on: ubuntu-latest 
    environment: ubuntu
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.7

    - name: Update Resume Gist
      uses: exuanbo/actions-deploy-gist@v1.1.4
      with:
        token: ${{ secrets.PAT }}
        gist_id: 6569cfc574c7d75f0c5c191342f8f637
        gist_description: "Amaury Van Espen Resume"
        file_path: resume.json
